spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=ADD_YOUR_ISSUER
clerk.jwks-url=ADD_YOUR_JWKS_URL
clerk.webhook.secret=ADD_YOUR_WEBHOOK_SECRET