spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

server.servlet.context-path=/api/v1.0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${ADD_YOUR_ISSUER}
clerk.jwks-url=${ADD_YOUR_JWKS_URL}
clerk.webhook.secret=${ADD_YOUR_WEBHOOK_SECRET}

stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

app.frontend.url=${APP_FRONTEND_URL}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=125MB